# Generated by Django 5.2.7 on 2025-11-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='raw_callback',
        ),
    ]
