# Generated by Django 5.2.7 on 2025-11-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_payment_method_remove_payment_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_status',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('NONE', 'Belum Dikirim'), ('ON_PROCESS', 'Diproses Gudang'), ('ON_DELIVERY', 'Dalam Pengiriman'), ('DELIVERED', 'Terkirim')], default='NONE', max_length=20),
        ),
    ]
