# Generated by Django 5.2.7 on 2026-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orderitem_quantity_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/custom_designs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
