# Generated by Django 5.2.7 on 2026-04-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderitem_custom_image_orderitem_custom_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='custom_service_name',
            new_name='custom_variant_name',
        ),
    ]
