# Generated by Django 5.2.7 on 2026-04-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_custom_service_name_orderitem_custom_variant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='custom_variant_name',
            new_name='custom_service_name',
        ),
    ]
