# Generated by Django 5.2.7 on 2026-04-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_custom_variant_name_orderitem_custom_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_notes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_service_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_custom',
        ),
    ]
