# Generated by Django 5.2.7 on 2026-04-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_orderitem_custom_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('SABLON', 'Sablon'), ('BORDIR', 'Bordir')], max_length=20)),
                ('additional_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='custom_products/')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('available_services', models.ManyToManyField(to='shop.customservice')),
            ],
        ),
    ]
