# Generated by Django 5.2.7 on 2026-04-07 16:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customservice_customproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp/custom_designs/'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customservice'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/custom_designs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='available_services',
            field=models.ManyToManyField(related_name='custom_products', to='shop.customservice'),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Pilih produk polos dasar', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
