# Generated by Django 5.2.7 on 2026-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cartitem_unique_together_cartitem_custom_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
