# Generated by Django 5.2.7 on 2026-04-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customproduct_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_stock',
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='base_product',
            field=models.ForeignKey(help_text='Produk polos yang digunakan sebagai bahan', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Harga dasar produk polos', max_digits=12),
        ),
        migrations.CreateModel(
            name='CustomProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga baju khusus ukuran ini untuk paket kustom', max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stok khusus untuk jalur kustom')),
                ('custom_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.customproduct')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.size')),
            ],
            options={
                'unique_together': {('custom_product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customproductvariant'),
        ),
    ]
