# Generated by Django 5.2.7 on 2026-05-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_payment_external_id_payment_invoice_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
    ]
