# Generated by Django 5.2.7 on 2026-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_payment_external_id_payment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_products/'),
        ),
    ]
