# Generated by Django 5.2.7 on 2026-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_estimation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Diproses'), ('PROCESSING', 'Sedang Diproses'), ('SHIPPED', 'Sedang Dikirim'), ('DELIVERED', 'Pesanan Sampai')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
