# Generated by Django 5.2.7 on 2026-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_destination_subdistrict_id_order_total_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='destination_subdistrict_id',
            new_name='city_id',
        ),
        migrations.AddField(
            model_name='order',
            name='province_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subdistrict_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
