# Generated by Django 5.2.7 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_destination_subdistrict_id_order_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='province_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='subdistrict_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
