# Generated by Django 5.2.7 on 2026-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_customer_city_id_customer_province_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_subdistrict_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
